[package]
name = "yaus"
version = "0.1.0"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]

[dependencies]
chrono = "0.2.22"
iron = "0.3.0"
lazy_static = "0.2.1"
router = "0.1.1"
rusqlite = "0.7.3"
sha2 = "0.1.2"
url = "1.1.1"
