[package]
name = "yaus"
version = "0.1.1"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]

[dependencies]
chrono = "0.2.22"
iron = "0.3.0"
persistent = "0.1.0"
r2d2 = "0.7.0"
r2d2_sqlite = "0.1.0"
router = "0.1.1"
rusqlite = "0.7.3"
sha2 = "0.1.2"
